const countryData = [
  { label: 'Afghanistan', value: 'AF', flag: 'https://flagcdn.com/w320/af.png', phoneCode: '+93' },
  { label: 'Albania', value: 'AL', flag: 'https://flagcdn.com/w320/al.png', phoneCode: '+355' },
  { label: 'Algeria', value: 'DZ', flag: 'https://flagcdn.com/w320/dz.png', phoneCode: '+213' },
  { label: 'Andorra', value: 'AD', flag: 'https://flagcdn.com/w320/ad.png', phoneCode: '+376' },
  { label: 'Angola', value: 'AO', flag: 'https://flagcdn.com/w320/ao.png', phoneCode: '+244' },
  { label: 'Antigua and Barbuda', value: 'AG', flag: 'https://flagcdn.com/w320/ag.png', phoneCode: '+1-268' },
  { label: 'Argentina', value: 'AR', flag: 'https://flagcdn.com/w320/ar.png', phoneCode: '+54' },
  { label: 'Armenia', value: 'AM', flag: 'https://flagcdn.com/w320/am.png', phoneCode: '+374' },
  { label: 'Australia', value: 'AU', flag: 'https://flagcdn.com/w320/au.png', phoneCode: '+61' },
  { label: 'Austria', value: 'AT', flag: 'https://flagcdn.com/w320/at.png', phoneCode: '+43' },
  { label: 'Azerbaijan', value: 'AZ', flag: 'https://flagcdn.com/w320/az.png', phoneCode: '+994' },
  { label: 'Bahamas', value: 'BS', flag: 'https://flagcdn.com/w320/bs.png', phoneCode: '+1-242' },
  { label: 'Bahrain', value: 'BH', flag: 'https://flagcdn.com/w320/bh.png', phoneCode: '+973' },
  { label: 'Bangladesh', value: 'BD', flag: 'https://flagcdn.com/w320/bd.png', phoneCode: '+880' },
  { label: 'Barbados', value: 'BB', flag: 'https://flagcdn.com/w320/bb.png', phoneCode: '+1-246' },
  { label: 'Belarus', value: 'BY', flag: 'https://flagcdn.com/w320/by.png', phoneCode: '+375' },
  { label: 'Belgium', value: 'BE', flag: 'https://flagcdn.com/w320/be.png', phoneCode: '+32' },
  { label: 'Belize', value: 'BZ', flag: 'https://flagcdn.com/w320/bz.png', phoneCode: '+501' },
  { label: 'Benin', value: 'BJ', flag: 'https://flagcdn.com/w320/bj.png', phoneCode: '+229' },
  { label: 'Bhutan', value: 'BT', flag: 'https://flagcdn.com/w320/bt.png', phoneCode: '+975' },
  { label: 'Bolivia', value: 'BO', flag: 'https://flagcdn.com/w320/bo.png', phoneCode: '+591' },
  { label: 'Bosnia and Herzegovina', value: 'BA', flag: 'https://flagcdn.com/w320/ba.png', phoneCode: '+387' },
  { label: 'Botswana', value: 'BW', flag: 'https://flagcdn.com/w320/bw.png', phoneCode: '+267' },
  { label: 'Brazil', value: 'BR', flag: 'https://flagcdn.com/w320/br.png', phoneCode: '+55' },
  { label: 'Brunei', value: 'BN', flag: 'https://flagcdn.com/w320/bn.png', phoneCode: '+673' },
  { label: 'Bulgaria', value: 'BG', flag: 'https://flagcdn.com/w320/bg.png', phoneCode: '+359' },
  { label: 'Burkina Faso', value: 'BF', flag: 'https://flagcdn.com/w320/bf.png', phoneCode: '+226' },
  { label: 'Burundi', value: 'BI', flag: 'https://flagcdn.com/w320/bi.png', phoneCode: '+257' },
  { label: 'Cabo Verde', value: 'CV', flag: 'https://flagcdn.com/w320/cv.png', phoneCode: '+238' },
  { label: 'Cambodia', value: 'KH', flag: 'https://flagcdn.com/w320/kh.png', phoneCode: '+855' },
  { label: 'Cameroon', value: 'CM', flag: 'https://flagcdn.com/w320/cm.png', phoneCode: '+237' },
  { label: 'Canada', value: 'CA', flag: 'https://flagcdn.com/w320/ca.png', phoneCode: '+1' },
  { label: 'Central African Republic', value: 'CF', flag: 'https://flagcdn.com/w320/cf.png', phoneCode: '+236' },
  { label: 'Chad', value: 'TD', flag: 'https://flagcdn.com/w320/td.png', phoneCode: '+235' },
  { label: 'Chile', value: 'CL', flag: 'https://flagcdn.com/w320/cl.png', phoneCode: '+56' },
  { label: 'China', value: 'CN', flag: 'https://flagcdn.com/w320/cn.png', phoneCode: '+86' },
  { label: 'Colombia', value: 'CO', flag: 'https://flagcdn.com/w320/co.png', phoneCode: '+57' },
  { label: 'Comoros', value: 'KM', flag: 'https://flagcdn.com/w320/km.png', phoneCode: '+269' },
  { label: 'Congo', value: 'CG', flag: 'https://flagcdn.com/w320/cg.png', phoneCode: '+242' },
  { label: 'Congo (DRC)', value: 'CD', flag: 'https://flagcdn.com/w320/cd.png', phoneCode: '+243' },
  { label: 'Costa Rica', value: 'CR', flag: 'https://flagcdn.com/w320/cr.png', phoneCode: '+506' },
  { label: 'Croatia', value: 'HR', flag: 'https://flagcdn.com/w320/hr.png', phoneCode: '+385' },
  { label: 'Cuba', value: 'CU', flag: 'https://flagcdn.com/w320/cu.png', phoneCode: '+53' },
  { label: 'Cyprus', value: 'CY', flag: 'https://flagcdn.com/w320/cy.png', phoneCode: '+357' },
  { label: 'Czechia', value: 'CZ', flag: 'https://flagcdn.com/w320/cz.png', phoneCode: '+420' },
  { label: 'Denmark', value: 'DK', flag: 'https://flagcdn.com/w320/dk.png', phoneCode: '+45' },
  { label: 'Djibouti', value: 'DJ', flag: 'https://flagcdn.com/w320/dj.png', phoneCode: '+253' },
  { label: 'Dominica', value: 'DM', flag: 'https://flagcdn.com/w320/dm.png', phoneCode: '+1-767' },
  { label: 'Dominican Republic', value: 'DO', flag: 'https://flagcdn.com/w320/do.png', phoneCode: '+1-809' },
  { label: 'Ecuador', value: 'EC', flag: 'https://flagcdn.com/w320/ec.png', phoneCode: '+593' },
  { label: 'Egypt', value: 'EG', flag: 'https://flagcdn.com/w320/eg.png', phoneCode: '+20' },
  { label: 'El Salvador', value: 'SV', flag: 'https://flagcdn.com/w320/sv.png', phoneCode: '+503' },
  { label: 'Equatorial Guinea', value: 'GQ', flag: 'https://flagcdn.com/w320/gq.png', phoneCode: '+240' },
  { label: 'Eritrea', value: 'ER', flag: 'https://flagcdn.com/w320/er.png', phoneCode: '+291' },
  { label: 'Estonia', value: 'EE', flag: 'https://flagcdn.com/w320/ee.png', phoneCode: '+372' },
  { label: 'Eswatini', value: 'SZ', flag: 'https://flagcdn.com/w320/sz.png', phoneCode: '+268' },
  { label: 'Ethiopia', value: 'ET', flag: 'https://flagcdn.com/w320/et.png', phoneCode: '+251' },
  { label: 'Fiji', value: 'FJ', flag: 'https://flagcdn.com/w320/fj.png', phoneCode: '+679' },
  { label: 'Finland', value: 'FI', flag: 'https://flagcdn.com/w320/fi.png', phoneCode: '+358' },
  { label: 'France', value: 'FR', flag: 'https://flagcdn.com/w320/fr.png', phoneCode: '+33' },
  { label: 'Gabon', value: 'GA', flag: 'https://flagcdn.com/w320/ga.png', phoneCode: '+241' },
  { label: 'Gambia', value: 'GM', flag: 'https://flagcdn.com/w320/gm.png', phoneCode: '+220' },
  { label: 'Georgia', value: 'GE', flag: 'https://flagcdn.com/w320/ge.png', phoneCode: '+995' },
  { label: 'Germany', value: 'DE', flag: 'https://flagcdn.com/w320/de.png', phoneCode: '+49' },
  { label: 'Ghana', value: 'GH', flag: 'https://flagcdn.com/w320/gh.png', phoneCode: '+233' },
  { label: 'Greece', value: 'GR', flag: 'https://flagcdn.com/w320/gr.png', phoneCode: '+30' },
  { label: 'Grenada', value: 'GD', flag: 'https://flagcdn.com/w320/gd.png', phoneCode: '+1-473' },
  { label: 'Guatemala', value: 'GT', flag: 'https://flagcdn.com/w320/gt.png', phoneCode: '+502' },
  { label: 'Guinea', value: 'GN', flag: 'https://flagcdn.com/w320/gn.png', phoneCode: '+224' },
  { label: 'Guinea-Bissau', value: 'GW', flag: 'https://flagcdn.com/w320/gw.png', phoneCode: '+245' },
  { label: 'Guyana', value: 'GY', flag: 'https://flagcdn.com/w320/gy.png', phoneCode: '+592' },
  { label: 'Haiti', value: 'HT', flag: 'https://flagcdn.com/w320/ht.png', phoneCode: '+509' },
  { label: 'Honduras', value: 'HN', flag: 'https://flagcdn.com/w320/hn.png', phoneCode: '+504' },
  { label: 'Hungary', value: 'HU', flag: 'https://flagcdn.com/w320/hu.png', phoneCode: '+36' },
  { label: 'Iceland', value: 'IS', flag: 'https://flagcdn.com/w320/is.png', phoneCode: '+354' },
  { label: 'India', value: 'IN', flag: 'https://flagcdn.com/w320/in.png', phoneCode: '+91' },
  { label: 'Indonesia', value: 'ID', flag: 'https://flagcdn.com/w320/id.png', phoneCode: '+62' },
  { label: 'Iran', value: 'IR', flag: 'https://flagcdn.com/w320/ir.png', phoneCode: '+98' },
  { label: 'Iraq', value: 'IQ', flag: 'https://flagcdn.com/w320/iq.png', phoneCode: '+964' },
  { label: 'Ireland', value: 'IE', flag: 'https://flagcdn.com/w320/ie.png', phoneCode: '+353' },
  { label: 'Israel', value: 'IL', flag: 'https://flagcdn.com/w320/il.png', phoneCode: '+972' },
  { label: 'Italy', value: 'IT', flag: 'https://flagcdn.com/w320/it.png', phoneCode: '+39' },
  { label: 'Jamaica', value: 'JM', flag: 'https://flagcdn.com/w320/jm.png', phoneCode: '+1-876' },
  { label: 'Japan', value: 'JP', flag: 'https://flagcdn.com/w320/jp.png', phoneCode: '+81' },
  { label: 'Jordan', value: 'JO', flag: 'https://flagcdn.com/w320/jo.png', phoneCode: '+962' },
  { label: 'Kazakhstan', value: 'KZ', flag: 'https://flagcdn.com/w320/kz.png', phoneCode: '+7' },
  { label: 'Kenya', value: 'KE', flag: 'https://flagcdn.com/w320/ke.png', phoneCode: '+254' },
  { label: 'Kiribati', value: 'KI', flag: 'https://flagcdn.com/w320/ki.png', phoneCode: '+686' },
  { label: 'Kuwait', value: 'KW', flag: 'https://flagcdn.com/w320/kw.png', phoneCode: '+965' },
  { label: 'Kyrgyzstan', value: 'KG', flag: 'https://flagcdn.com/w320/kg.png', phoneCode: '+996' },
  { label: 'Laos', value: 'LA', flag: 'https://flagcdn.com/w320/la.png', phoneCode: '+856' },
  { label: 'Latvia', value: 'LV', flag: 'https://flagcdn.com/w320/lv.png', phoneCode: '+371' },
  { label: 'Lebanon', value: 'LB', flag: 'https://flagcdn.com/w320/lb.png', phoneCode: '+961' },
  { label: 'Lesotho', value: 'LS', flag: 'https://flagcdn.com/w320/ls.png', phoneCode: '+266' },
  { label: 'Liberia', value: 'LR', flag: 'https://flagcdn.com/w320/lr.png', phoneCode: '+231' },
  { label: 'Libya', value: 'LY', flag: 'https://flagcdn.com/w320/ly.png', phoneCode: '+218' },
  { label: 'Liechtenstein', value: 'LI', flag: 'https://flagcdn.com/w320/li.png', phoneCode: '+423' },
  { label: 'Lithuania', value: 'LT', flag: 'https://flagcdn.com/w320/lt.png', phoneCode: '+370' },
  { label: 'Luxembourg', value: 'LU', flag: 'https://flagcdn.com/w320/lu.png', phoneCode: '+352' },
  { label: 'Madagascar', value: 'MG', flag: 'https://flagcdn.com/w320/mg.png', phoneCode: '+261' },
  { label: 'Malawi', value: 'MW', flag: 'https://flagcdn.com/w320/mw.png', phoneCode: '+265' },
  { label: 'Malaysia', value: 'MY', flag: 'https://flagcdn.com/w320/my.png', phoneCode: '+60' },
  { label: 'Maldives', value: 'MV', flag: 'https://flagcdn.com/w320/mv.png', phoneCode: '+960' },
  { label: 'Mali', value: 'ML', flag: 'https://flagcdn.com/w320/ml.png', phoneCode: '+223' },
  { label: 'Malta', value: 'MT', flag: 'https://flagcdn.com/w320/mt.png', phoneCode: '+356' },
  { label: 'Marshall Islands', value: 'MH', flag: 'https://flagcdn.com/w320/mh.png', phoneCode: '+692' },
  { label: 'Mauritania', value: 'MR', flag: 'https://flagcdn.com/w320/mr.png', phoneCode: '+222' },
  { label: 'Mauritius', value: 'MU', flag: 'https://flagcdn.com/w320/mu.png', phoneCode: '+230' },
  { label: 'Mexico', value: 'MX', flag: 'https://flagcdn.com/w320/mx.png', phoneCode: '+52' },
  { label: 'Micronesia', value: 'FM', flag: 'https://flagcdn.com/w320/fm.png', phoneCode: '+691' },
  { label: 'Moldova', value: 'MD', flag: 'https://flagcdn.com/w320/md.png', phoneCode: '+373' },
  { label: 'Monaco', value: 'MC', flag: 'https://flagcdn.com/w320/mc.png', phoneCode: '+377' },
  { label: 'Mongolia', value: 'MN', flag: 'https://flagcdn.com/w320/mn.png', phoneCode: '+976' },
  { label: 'Montenegro', value: 'ME', flag: 'https://flagcdn.com/w320/me.png', phoneCode: '+382' },
  { label: 'Morocco', value: 'MA', flag: 'https://flagcdn.com/w320/ma.png', phoneCode: '+212' },
  { label: 'Mozambique', value: 'MZ', flag: 'https://flagcdn.com/w320/mz.png', phoneCode: '+258' },
  { label: 'Myanmar', value: 'MM', flag: 'https://flagcdn.com/w320/mm.png', phoneCode: '+95' },
  { label: 'Namibia', value: 'NA', flag: 'https://flagcdn.com/w320/na.png', phoneCode: '+264' },
  { label: 'Nauru', value: 'NR', flag: 'https://flagcdn.com/w320/nr.png', phoneCode: '+674' },
  { label: 'Nepal', value: 'NP', flag: 'https://flagcdn.com/w320/np.png', phoneCode: '+977' },
  { label: 'Netherlands', value: 'NL', flag: 'https://flagcdn.com/w320/nl.png', phoneCode: '+31' },
  { label: 'New Zealand', value: 'NZ', flag: 'https://flagcdn.com/w320/nz.png', phoneCode: '+64' },
  { label: 'Nicaragua', value: 'NI', flag: 'https://flagcdn.com/w320/ni.png', phoneCode: '+505' },
  { label: 'Niger', value: 'NE', flag: 'https://flagcdn.com/w320/ne.png', phoneCode: '+227' },
  { label: 'Nigeria', value: 'NG', flag: 'https://flagcdn.com/w320/ng.png', phoneCode: '+234' },
  { label: 'North Macedonia', value: 'MK', flag: 'https://flagcdn.com/w320/mk.png', phoneCode: '+389' },
  { label: 'Norway', value: 'NO', flag: 'https://flagcdn.com/w320/no.png', phoneCode: '+47' },
  { label: 'Oman', value: 'OM', flag: 'https://flagcdn.com/w320/om.png', phoneCode: '+968' },
  { label: 'Pakistan', value: 'PK', flag: 'https://flagcdn.com/w320/pk.png', phoneCode: '+92' },
  { label: 'Palau', value: 'PW', flag: 'https://flagcdn.com/w320/pw.png', phoneCode: '+680' },
  { label: 'Palestine', value: 'PS', flag: 'https://flagcdn.com/w320/ps.png', phoneCode: '+970' },
  { label: 'Panama', value: 'PA', flag: 'https://flagcdn.com/w320/pa.png', phoneCode: '+507' },
  { label: 'Papua New Guinea', value: 'PG', flag: 'https://flagcdn.com/w320/pg.png', phoneCode: '+675' },
  { label: 'Paraguay', value: 'PY', flag: 'https://flagcdn.com/w320/py.png', phoneCode: '+595' },
  { label: 'Peru', value: 'PE', flag: 'https://flagcdn.com/w320/pe.png', phoneCode: '+51' },
  { label: 'Philippines', value: 'PH', flag: 'https://flagcdn.com/w320/ph.png', phoneCode: '+63' },
  { label: 'Poland', value: 'PL', flag: 'https://flagcdn.com/w320/pl.png', phoneCode: '+48' },
  { label: 'Portugal', value: 'PT', flag: 'https://flagcdn.com/w320/pt.png', phoneCode: '+351' },
  { label: 'Qatar', value: 'QA', flag: 'https://flagcdn.com/w320/qa.png', phoneCode: '+974' },
  { label: 'Romania', value: 'RO', flag: 'https://flagcdn.com/w320/ro.png', phoneCode: '+40' },
  { label: 'Russia', value: 'RU', flag: 'https://flagcdn.com/w320/ru.png', phoneCode: '+7' },
  { label: 'Rwanda', value: 'RW', flag: 'https://flagcdn.com/w320/rw.png', phoneCode: '+250' },
  { label: 'Saint Kitts and Nevis', value: 'KN', flag: 'https://flagcdn.com/w320/kn.png', phoneCode: '+1-869' },
  { label: 'Saint Lucia', value: 'LC', flag: 'https://flagcdn.com/w320/lc.png', phoneCode: '+1-758' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC', flag: 'https://flagcdn.com/w320/vc.png', phoneCode: '+1-784' },
  { label: 'Samoa', value: 'WS', flag: 'https://flagcdn.com/w320/ws.png', phoneCode: '+685' },
  { label: 'San Marino', value: 'SM', flag: 'https://flagcdn.com/w320/sm.png', phoneCode: '+378' },
  { label: 'Sao Tome and Principe', value: 'ST', flag: 'https://flagcdn.com/w320/st.png', phoneCode: '+239' },
  { label: 'Saudi Arabia', value: 'SA', flag: 'https://flagcdn.com/w320/sa.png', phoneCode: '+966' },
  { label: 'Senegal', value: 'SN', flag: 'https://flagcdn.com/w320/sn.png', phoneCode: '+221' },
  { label: 'Serbia', value: 'RS', flag: 'https://flagcdn.com/w320/rs.png', phoneCode: '+381' },
  { label: 'Seychelles', value: 'SC', flag: 'https://flagcdn.com/w320/sc.png', phoneCode: '+248' },
  { label: 'Sierra Leone', value: 'SL', flag: 'https://flagcdn.com/w320/sl.png', phoneCode: '+232' },
  { label: 'Singapore', value: 'SG', flag: 'https://flagcdn.com/w320/sg.png', phoneCode: '+65' },
  { label: 'Slovakia', value: 'SK', flag: 'https://flagcdn.com/w320/sk.png', phoneCode: '+421' },
  { label: 'Slovenia', value: 'SI', flag: 'https://flagcdn.com/w320/si.png', phoneCode: '+386' },
  { label: 'Solomon Islands', value: 'SB', flag: 'https://flagcdn.com/w320/sb.png', phoneCode: '+677' },
  { label: 'Somalia', value: 'SO', flag: 'https://flagcdn.com/w320/so.png', phoneCode: '+252' },
  { label: 'South Africa', value: 'ZA', flag: 'https://flagcdn.com/w320/za.png', phoneCode: '+27' },
  { label: 'South Korea', value: 'KR', flag: 'https://flagcdn.com/w320/kr.png', phoneCode: '+82' },
  { label: 'South Sudan', value: 'SS', flag: 'https://flagcdn.com/w320/ss.png', phoneCode: '+211' },
  { label: 'Spain', value: 'ES', flag: 'https://flagcdn.com/w320/es.png', phoneCode: '+34' },
  { label: 'Sri Lanka', value: 'LK', flag: 'https://flagcdn.com/w320/lk.png', phoneCode: '+94' },
  { label: 'Sudan', value: 'SD', flag: 'https://flagcdn.com/w320/sd.png', phoneCode: '+249' },
  { label: 'Suriname', value: 'SR', flag: 'https://flagcdn.com/w320/sr.png', phoneCode: '+597' },
  { label: 'Sweden', value: 'SE', flag: 'https://flagcdn.com/w320/se.png', phoneCode: '+46' },
  { label: 'Switzerland', value: 'CH', flag: 'https://flagcdn.com/w320/ch.png', phoneCode: '+41' },
  { label: 'Syria', value: 'SY', flag: 'https://flagcdn.com/w320/sy.png', phoneCode: '+963' },
  { label: 'Taiwan', value: 'TW', flag: 'https://flagcdn.com/w320/tw.png', phoneCode: '+886' },
  { label: 'Tajikistan', value: 'TJ', flag: 'https://flagcdn.com/w320/tj.png', phoneCode: '+992' },
  { label: 'Tanzania', value: 'TZ', flag: 'https://flagcdn.com/w320/tz.png', phoneCode: '+255' },
  { label: 'Thailand', value: 'TH', flag: 'https://flagcdn.com/w320/th.png', phoneCode: '+66' },
  { label: 'Timor-Leste', value: 'TL', flag: 'https://flagcdn.com/w320/tl.png', phoneCode: '+670' },
  { label: 'Togo', value: 'TG', flag: 'https://flagcdn.com/w320/tg.png', phoneCode: '+228' },
  { label: 'Tonga', value: 'TO', flag: 'https://flagcdn.com/w320/to.png', phoneCode: '+676' },
  { label: 'Trinidad and Tobago', value: 'TT', flag: 'https://flagcdn.com/w320/tt.png', phoneCode: '+1-868' },
  { label: 'Tunisia', value: 'TN', flag: 'https://flagcdn.com/w320/tn.png', phoneCode: '+216' },
  { label: 'Turkey', value: 'TR', flag: 'https://flagcdn.com/w320/tr.png', phoneCode: '+90' },
  { label: 'Turkmenistan', value: 'TM', flag: 'https://flagcdn.com/w320/tm.png', phoneCode: '+993' },
  { label: 'Tuvalu', value: 'TV', flag: 'https://flagcdn.com/w320/tv.png', phoneCode: '+688' },
  { label: 'Uganda', value: 'UG', flag: 'https://flagcdn.com/w320/ug.png', phoneCode: '+256' },
  { label: 'Ukraine', value: 'UA', flag: 'https://flagcdn.com/w320/ua.png', phoneCode: '+380' },
  { label: 'United Arab Emirates', value: 'AE', flag: 'https://flagcdn.com/w320/ae.png', phoneCode: '+971' },
  { label: 'United Kingdom', value: 'GB', flag: 'https://flagcdn.com/w320/gb.png', phoneCode: '+44' },
  { label: 'United States', value: 'US', flag: 'https://flagcdn.com/w320/us.png', phoneCode: '+1' },
  { label: 'Uruguay', value: 'UY', flag: 'https://flagcdn.com/w320/uy.png', phoneCode: '+598' },
  { label: 'Uzbekistan', value: 'UZ', flag: 'https://flagcdn.com/w320/uz.png', phoneCode: '+998' },
  { label: 'Vanuatu', value: 'VU', flag: 'https://flagcdn.com/w320/vu.png', phoneCode: '+678' },
  { label: 'Vatican City', value: 'VA', flag: 'https://flagcdn.com/w320/va.png', phoneCode: '+379' },
  { label: 'Venezuela', value: 'VE', flag: 'https://flagcdn.com/w320/ve.png', phoneCode: '+58' },
  { label: 'Vietnam', value: 'VN', flag: 'https://flagcdn.com/w320/vn.png', phoneCode: '+84' },
  { label: 'Yemen', value: 'YE', flag: 'https://flagcdn.com/w320/ye.png', phoneCode: '+967' },
  { label: 'Zambia', value: 'ZM', flag: 'https://flagcdn.com/w320/zm.png', phoneCode: '+260' },
  { label: 'Zimbabwe', value: 'ZW', flag: 'https://flagcdn.com/w320/zw.png', phoneCode: '+263' }
]

export  {countryData};
